### ISSUE TITLE
Tampilan Tidak Sesuai Harapan <aside>

### ISSUE THREAD

**Issue by asepdwisaputra** [asepdwisaputra/DBSF_Frontend-2024#1]
Jadi di [01_Dasar-Web/04_Pendalaman-CSS/index-5.html](https://github.com/asepdwisaputra/DBSF_Frontend-2024/blob/main/01_Dasar-Web/04_Pendalaman-CSS/index-5.html), saya sedang membuat sebuah web untuk latihan dimana ada bagian aside yang ingin saya tampilkan disebelah kanan layar, namun tidak sesuai harapan.

<img width="947" alt="Tampilan Full Harapan" src="https://github.com/asepdwisaputra/DBSF_Frontend-2024/assets/127648406/2900327d-81bc-4ae5-afcd-67cee500000e">
<img width="256" alt="Ketika di mobile aside tidak sesuai harapan" src="https://github.com/asepdwisaputra/DBSF_Frontend-2024/assets/127648406/1267c566-4b1d-47e2-b9ad-3d6674c32cb1">

**Comment by asepdwisaputra** [comment]
Di tampilan mobile dibawah bagian kiri nampak tepotong, mohon pencerahannya

**Comment by aguradev** [comment]
diantara `div id="content"` `aside` bisa dibungkus menggunakan div dan memiliki class khusus yang mengelola layout 

biasanya menggunakan sebuah `display: flex` atau `display: grid`;

bisa di lihat untuk lebih lanjut

https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by asepdwisaputra** [comment]
`
#content {
          float: left;
          width: 75%;
        }
        
aside {
     float: right;
     width: 20%;
     padding-left: 20px;
 }
`

apakah mungkin jika width di tag aside memakai 25%?, ketika saya coba itu akan menabrak dan tertinggal di bawah

**Comment by aguradev** [comment]
untuk `padding-left:20px;` bisa diatur juga di bagian mobile supaya responsive

`
@media(max-width:600px){
aside {
padding-left:0px;
}
}
`

lebih lanjut mengenai responsive queries

https://www.w3schools.com/css/css_rwd_mediaqueries.asp
