### ISSUE TITLE
Bagaimana meletakan profil kota(aside) di sebelah kiri layar

### ISSUE THREAD

**Issue by asepdwisaputra** [asepdwisaputra/DBSF_Frontend-2024#2]
Saya sudah mencoba namun sampai sekarang belum menenukan cara untuk memindahkan <aside> ke sisi kanan layar saya dengan baik. Bila kamu berkenan mohon dibantu 😭👌

**Kode**
[01_Dasar-Web/04_Pendalaman-CSS/index-5.html](https://github.com/asepdwisaputra/DBSF_Frontend-2024/blob/main/01_Dasar-Web/04_Pendalaman-CSS/index-5.html)

**Tampilan Mobile dan Tampilan Sekarang**
<img width="265" alt="Tampilan Sekarang" src="https://github.com/asepdwisaputra/DBSF_Frontend-2024/assets/127648406/31ff5032-243f-40fd-b531-75fc3d956ab4">

**Harapan Ketika Layar Lebar**
<img width="947" alt="Tampilan Full Harapan" src="https://github.com/asepdwisaputra/DBSF_Frontend-2024/assets/127648406/60cce607-9eb6-4dd3-94c5-e5a3175a547e">

**Kendala Saya**
- Card Profile sudah dikanan tapi tidak ke atas
- Card sudah ke atas namun terkadang terpotong, sehingga perlu gulir ke kanan.

**Comment by imaulanaazn** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Halaman Profil Bandung - Mobile Version</title>

    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;700&display=swap" rel="stylesheet">
    
    <style>
        .jumbotron {
          font-size: 20px;
          padding: 60px;
          background-color: #00c8eb;
          text-align: center;
          color: white;
        }

        body{
          font-family:'Quicksand', sans-serif;

          margin: 0px;
          padding: 0px;
        }

        main{
          overflow: auto;
          margin: 0;
          padding: 0px;
          display: flex;
        }
        
	aside{
	min-width: 400px;
	height: max-content;
	}

        h2, h3 {
          color: #00a2c6;
        }
 
        footer {
          padding: 20px;
          color: white;
          background-color: #00a2c6;
          text-align: center;
        }
        
        nav a {
          font-size: 18px;
          font-weight: 400;
          text-decoration: none;

          color: white;
        }

        nav a:hover {
          font-weight: bold;
        }

        .profile{
          text-align: center;
        }

        .featured-image {
          width: 100%;
          max-height: 300px;
          object-fit: cover;
          object-position: center;
        }

        .profile img{
          width: 200px;
          height: auto;
        }

        .card{
          box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); /*kaki, tasbaw, buram, luasburam, warna*/
          border-radius: 5px;

          /* height: fit-content; */

          margin: 20px;
          padding: 20px;
        }

        nav li{
          display: inline;
          list-style-type: none;
          margin-right: 20px;
        }

        nav{
          background-color: #00a2c6;
          padding: 5px;

          position: sticky;
          top: 0;
        }

        header{
          display: inline;
        }
        
        aside {
          display: flex;
          flex-direction: column; /* Menetapkan tata letak anak-anak menjadi kolom */
          justify-content: center; /* Menyusun anak-anak di tengah secara vertikal */
          align-items: center; /* Menyusun anak-anak di tengah secara horizontal */
          margin: 0;
        }
        
        @media screen and (max-width: 1000px) {
          #content, aside {
            padding: 0px;
          }
        }
    </style>

  </head>

  <body>
    <header>
      <div class="jumbotron">
        <h1>Bandung</h1>
        <p>
          Kota metropolitan terbesar di Provinsi Jawa Barat, sekaligus menjadi ibu kota provinsi
          tersebut.
        </p>
      </div>

      <nav>
        <ul>
          <li>
            <a href="#sejarah">Sejarah</a>
          </li>
          <li>
            <a href="#geografis">Geografis</a>
          </li>
          <li>
            <a href="#wisata">Wisata</a>
          </li>
        </ul>
      </nav>
    </header>

    <main>
      
      <div id="content">
        <article id="sejarah" class="card">
          <h2>Sejarah</h2>
          <img class="featured-image" src="/image/history.jpg" alt="sejarah"  />
          <p>
            Kata Bandung berasal dari kata bendung atau bendungan karena terbendungnya sungai
            Citarum oleh lava Gunung Tangkuban Parahu yang lalu membentuk telaga. Legenda yang
            diceritakan oleh orang-orang tua di Bandung mengatakan bahwa nama Bandung diambil dari
            sebuah kendaraan air yang terdiri dari dua perahu yang diikat berdampingan yang disebut
            perahu bandung yang digunakan oleh Bupati Bandung, R.A. Wiranatakusumah II, untuk
            melayari Ci Tarum dalam mencari tempat kedudukan kabupaten yang baru untuk menggantikan
            ibu kota yang lama di Dayeuhkolot.
          </p>

          <p>
            Berdasarkan filosofi Sunda, kata Bandung juga berasal dari kalimat Nga-Bandung-an Banda
            Indung, yang merupakan kalimat sakral dan luhur karena mengandung nilai ajaran Sunda.
            Nga-Bandung-an artinya menyaksikan atau bersaksi. Banda adalah segala sesuatu yang
            berada di alam hidup yaitu di bumi dan atmosfer, baik makhluk hidup maupun benda mati.
            Sinonim dari banda adalah harta. Indung berarti Ibu atau Bumi, disebut juga sebagai Ibu
            Pertiwi tempat Banda berada.
          </p>
        </article>

        <article id="geografis" class="card">
          <h2>Geografis</h2>
          <img src="/image/geografis.jpg" alt="geografis" class="featured-image" />
          <p>
            Kota Bandung dikelilingi oleh pegunungan, sehingga bentuk morfologi wilayahnya bagaikan
            sebuah mangkok raksasa,[9] secara geografis kota ini terletak di tengah-tengah provinsi
            Jawa Barat, serta berada pada ketinggian ±768 m di atas permukaan laut, dengan titik
            tertinggi di berada di sebelah utara dengan ketinggian 1.050 meter di atas permukaan
            laut dan sebelah selatan merupakan kawasan rendah dengan ketinggian 675 meter di atas
            permukaan laut.
          </p>

          <p>
            Kota Bandung dialiri dua sungai utama, yaitu Sungai Cikapundung dan Sungai Citarum
            beserta anak-anak sungainya yang pada umumnya mengalir ke arah selatan dan bertemu di
            Sungai Citarum. Dengan kondisi yang demikian, Bandung selatan sangat rentan terhadap
            masalah banjir terutama pada musim hujan.
          </p>
        </article>

        <article id="wisata" class="card">
          <h2>Wisata</h2>
          <p>
            Sejak dibukanya Jalan Tol Cipularang, kota Bandung telah menjadi tujuan utama dalam
            menikmati liburan akhir pekan terutama dari masyarakat yang berasal dari Jakarta
            sekitarnya. Selain menjadi kota wisata belanja, kota Bandung juga dikenal dengan
            sejumlah besar bangunan lama berarsitektur peninggalan Belanda.
          </p>

          <section>
            <h3>Farm House Lembang</h3>
            <img class="featured-image" src="/image/farm-house.jpg" alt="farm house"  />
            <p>
              Berada di jalur utama Bandung-Lembang, Farm House menjadi objek wisata yang tidak
              pernah sepi pengunjung. Selain karena letaknya strategis, kawasan ini juga
              menghadirkan nuansa wisata khas Eropa. Semua itu diterapkan dalam bentuk spot swafoto
              Instagramable.
            </p>
          </section>

          <section>
            <h3>Observatorium Bosscha</h3>
            <img class="featured-image" src="/image/bosscha.jpg" alt="bosscha"/>
            <p>
              Memiliki beberapa teleskop, antara lain, Refraktor Ganda Zeiss, Schmidt Bimasakti,
              Refraktor Bamberg, Cassegrain GOTO, dan Teleskop Surya. Refraktor Ganda Zeiss adalah
              jenis teleskop terbesar untuk meneropong bintang. Benda ini diletakkan pada atap kubah
              sehingga saat teropong digunakan, atap tersebut harus dibuka. Observatorium Bosscha
              boleh dikunjungi oleh siapapun, tanpa tiket. Namun, bagi yang ingin menggunakan
              teleskop Zeiss, wajib mendaftarkan diri. Untuk instansi atau lembaga pendidikan,
              diberikan jadwal hari Selasa sampai Jumat. Sementara itu, kunjungan individu dibuka
              setiap hari Sabtu.
            </p>
          </section>
        </article>
      </div>

      
      <aside class="profile card">
        <article>
          <header>
            <h2>
              Kota Bandung
            </h2>
            <p>
              Kota Kembang Paris van Java
            </p>
            <figure>
              <img src="/image/Bandung_coa.png" alt="gambar profile"/>
              <figcaption>Lambang</figcaption>
            </figure>
          </header>

          <section>
            <h3>Informasi Lainnya</h3>

            <table>
              <tr>
                <th>Negara</th>
                <td>Indonesia</td>
              </tr>
              <tr>
                <th>Hari jadi</th>
                <td>25 September 1810</td>
              </tr>
              <tr>
                <th>Luas Total</th>
                <td>167.67 km<sup>2</sup></td>
              </tr>
              <tr>
                <th>Bahasa Daerah</th>
                <td>Sunda</td>
              </tr>
              <tr>
                <th>Kode Telepon</th>
                <td>+62 22</td>
              </tr>
            </table>
          </section>
        </article>
      </aside>
    </main>

    <footer>
      <p>Belajar Dasar Pemrograman Web &#169; 2019, Dicoding Academy</p>
    </footer>
  </body>
</html>

**Comment by asepdwisaputra** [comment]
Bagaimana membuat "Profil Kota" berada dibawah Content* ketika lebar layar < 1000px

* saya harap lebar "Profil Kota" sama dengan content juga

**Comment by imaulanaazn** [comment]
> Bagaimana membuat "Profil Kota" berada dibawah Content* ketika lebar layar < 1000px
> 
> * saya harap lebar "Profil Kota" sama dengan content juga

aside {
flex: none;
}

**Comment by asepdwisaputra** [comment]
Sudah Terselesaikan Terimakasih yaa :)
