### ISSUE TITLE
Mengatasi Lebar Card

### ISSUE THREAD

**Issue by asepdwisaputra** [asepdwisaputra/DBSF_Frontend-2024#3]
Saya mengalami kendala di lebar card untuk #content dan aside yang panjangnya  berbeda, apabila kamu berkenan tolong bantu saya. Terimakasih.

**Kode**
[01_Dasar-Web/04_Pendalaman-CSS/index-5.html](https://github.com/asepdwisaputra/DBSF_Frontend-2024/blob/main/01_Dasar-Web/04_Pendalaman-CSS/index-5.html)

**Gambar**
<img width="373" alt="image" src="https://github.com/asepdwisaputra/DBSF_Frontend-2024/assets/127648406/413b79c0-2374-4c1d-950f-b5c6b5aef74f">

_Saya ingin itu sama panjangnya, karena  di  gambar saya perlu menggulir ke kanan untuk melihat penuh card aside_

**Comment by NicholasDevlin** [comment]
`@media screen and (max-width: 1000px) {
      main {
        display: flex;
        flex-flow: column;
      }
      #content,
      aside {
        width: 100%;
        display: block;
      }
    }`

**Comment by asepdwisaputra** [comment]
Masih belum nih ka, atau aku salah menerapkan ya :(

**Comment by NicholasDevlin** [comment]
ganti dari @media screen kemudian copas code ku, oh iya class="profile card" pindahin dari aside ke article @asepdwisaputra

**Comment by asepdwisaputra** [comment]
wooow bisa bang nikol, thx ya😭🚀🚀@NicholasDevlin

> ganti dari @media screen kemudian copas code ku, oh iya class="profile card" pindahin dari aside ke article @asepdwisaputra

bisa bangg @NicholasDevlin Thx yaa 😭🚀🚀
